### ISSUE TITLE
LayerPlatformException - Invalid App ID

### ISSUE THREAD

**Issue by wgoh** [Jana-Mobile/layer-python#6]
Thank you so much for this python library for Layer.

I got my staging App ID from the Layer console.

However, I encountered this error "The referenced App ID is invalid.". May I ask where can I get an App ID? Thanks!!

**Comment by clmns** [comment]
Try using just the app id without "layer:///apps/staging/".
Works this way for me!

**Comment by rschlaikjer** [comment]
As clmns says, you need to use just the UUID section of your layer app ID.
